---
server:
  port: 8001
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost    
---    
spring:
  profiles: eureka1
eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2/eureka/
server:
  port: 8002
  
---
spring: 
  profiles: eureka2
server:
  port: 8003
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1/eureka/
