---
spring: 
  application:
    name: location
server:
  port: 8011
endpoints:
  actuator:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  mappings:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false     
info:
  app:
    name: Location Service
    version: 1.0   
