---
spring: 
  application:
    name: location
server:
  port: 8011
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8001/eureka
endpoints:
  actuator:
    enabled: true
    sensitive: true
  info:
    enabled: true
