spring:
  application:
    name: zuul-proxy
server:
  port: 8005
zuul:
  host:
    max-per-route-connections: 10
    max-total-connections: 100
  routes:
    location-123:
      path: /location-service/**
      service-id: location-service
    distance:
      path: /distance-service/**
      service-id: distance  
