spring:
  application:
    name: zuul-proxy
server:
  port: 8005
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
zuul:
  host:
    max-per-route-connections: 10
    max-total-connections: 100
  routes:
    location:
      path: /location-service/**
      service-id: location
